### ISSUE TITLE
RESTful style parameters

### ISSUE THREAD

**Issue by SMAPPER** [lucashenning/logstash-filter-rest#14]
Not sure if I'm just not reading the documentation right but is it possible to send RESTful style parameters with this plugin?

For example, I can get http://domain.com?field=parameter&field2=parameter2 to work but I cannot get http://domain.com/field/parameter to work.  In truth, for what I'm doing field is always the same so I could set it statically but I need to submit a parameter to it using /parameter.

**Comment by gandalfb** [comment]
You may try using the fields within the url:
rest {
  request {
    url => "https://myrest.com/%{one}/%{two}"
...

The params section can be omitted.

**Comment by SMAPPER** [comment]
When I do this I am getting "Malformed escape pair" errors from Logstash.  Here is what I have:

rest {
          request => {
            url => "http://localhost:10004/measure/%{server_name}"
          }
          sprintf => true
          target => "ssl_server_name_frequency_score"
}
