### ISSUE TITLE
Install error - plugin version conflict

### ISSUE THREAD

**Issue by tawny-tran** [lucashenning/logstash-filter-rest#15]
I ran the following commands to install the plugin:
/usr/share/logstash/bin/logstash-plugin install logstash-filter-rest

Below is the output. I'm using logstash v5.0.1. I'm not familiar with the development side of logstash, so not sure how to fix this. Is this plugin compatible with logstash v5? It looks like it's compatible with logstash-codec-json version <3.0.0, but the codec plugin that is shipped with v5 is 3.0.2.

Validating logstash-filter-rest
Installing logstash-filter-rest
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-codec-json":
  In snapshot (Gemfile.lock):
    logstash-codec-json (= 3.0.2)

  In Gemfile:
    logstash-output-udp (>= 0) java depends on
      logstash-codec-json (>= 0) java

    logstash-output-udp (>= 0) java depends on
      logstash-codec-json (>= 0) java

    logstash-output-udp (>= 0) java depends on
      logstash-codec-json (>= 0) java

    logstash-output-udp (>= 0) java depends on
      logstash-codec-json (>= 0) java

    logstash-output-udp (>= 0) java depends on
      logstash-codec-json (>= 0) java

    logstash-output-udp (>= 0) java depends on
      logstash-codec-json (>= 0) java

    logstash-output-udp (>= 0) java depends on
      logstash-codec-json (>= 0) java

    logstash-output-udp (>= 0) java depends on
      logstash-codec-json (>= 0) java

    logstash-output-udp (>= 0) java depends on
      logstash-codec-json (>= 0) java

    logstash-filter-rest (>= 0) java depends on
      logstash-codec-json (< 3.0.0, >= 1.6.0) java

    logstash-output-udp (>= 0) java depends on
      logstash-codec-json (>= 0) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 5.0.1)

  In Gemfile:
    logstash-core-plugin-api (>= 0) java depends on
      logstash-core (= 5.0.1) java

    logstash-filter-rest (>= 0) java depends on
      logstash-core (< 2.0.0, >= 1.4.0) java

    logstash-core (>= 0) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

**Comment by gandalfb** [comment]
The command - as I believe - pulls the gem from rubygems.org

To make this logstash 5 compatible @lucashenning needs to publish latest v0.5.0

Until then you could build the gem yourself from source. And install from filesystem. 

Hope this points you into the right direction

**Comment by lucashenning** [comment]
Yes, sorry @gandalfb, I need to publish v.0.5.0. Will do so this weekend...

**Comment by lucashenning** [comment]
Okay, v0.5.0 is published. `/usr/share/logstash/bin/logstash-plugin install logstash-filter-rest` should work for logstash 5 now.
