### ISSUE TITLE
HTTP Client Error Handling 

### ISSUE THREAD

**Issue by kalmas** [lucashenning/logstash-filter-rest#16]
Errors thrown from the underlying http client (when `client.http()` is called) are not caught and can cause the entire logstash pipeline to crash.

I've been encountering these errors as the result of socket timeouts (uncaught `Manticore::SocketTimeout` errors). They can also be caused by providing an invalid host in the url field.

For my purposes, it would be better to simply tag the event as failed and move on instead of stopping the whole pipeline.

**Comment by lucashenning** [comment]
Solved and published as v0.5.1 Thanks @kalmas
