### ISSUE TITLE
Option to use HTTP proxy

### ISSUE THREAD

**Issue by jursonovicst** [lucashenning/logstash-filter-rest#18]
Hi Lucas,

I would really appreciate, if you would consider adding a feature to access the REST API through an HTTP proxy.

I intend to use your filter to query a geoip database via REST, but to avoid high load on the geoip server by ingesting millions of log lines, I have to cache my results. In our setup, the most straightforward solution would be to access the GeoIP server through a squid proxy, which can do caching.

I already checked, the HTTP api (logstash-mixin-http_client) does support proxy connection (config :proxy). could you please make this settings transparent in your filter config as well? I mean something like this:

```
 rest {
    request => {
      url => "http://example.com"
      proxyurl => "http://proxyhost:proxyport"
      ...
```

KR
Tamás

**Comment by gandalfb** [comment]
Hi,

this Setting should be handed over to the http client already. 

Have you tried to set the :proxy where the request URL is set as well?

Maybe worth a test case. 

https://github.com/logstash-plugins/logstash-mixin-http_client/blob/master/README.md

**Comment by gandalfb** [comment]
Good morning,

so I tried it within `cli` and it works for me:

```bash
bin/logstash --debug -e 'input { stdin{} } filter { rest { request => { url => "https://jsonplaceholder.typicode.com/posts" proxy => "http://10.x.x.x:3128" method => "post" params => { "userId" => "%{message}" } headers => { "Content-Type" => "application/json" } } target => 'rest' } } output {stdout { codec => rubydebug }}'
```

Produces some log lines including:

```bash
[2017-01-30T09:00:33,529][DEBUG][org.apache.http.impl.conn.DefaultHttpClientConnectionOperator] Connecting to /10.x.x.x:3128
[2017-01-30T09:00:33,545][DEBUG][org.apache.http.impl.conn.DefaultHttpClientConnectionOperator] Connection established 10.y.y.y:33894<->10.x.x.x:3128
```

Basically just add after your `url`
```bash
proxy => "http://10.x.x.x:3128"
```

and you should be good to go.

**Comment by jursonovicst** [comment]
Hi,

Yes, it is working, thank you for your hint!


KR
Tamás

**Comment by gandalfb** [comment]
@jursonovicst it can be closed then?

**Comment by jursonovicst** [comment]
@gandalfb Yes, it is working, you may close this issue!
