### ISSUE TITLE
Double Escape Issue with Multiple Workers

### ISSUE THREAD

**Issue by tjgeorgen-zz** [lucashenning/logstash-filter-rest#22]
Using multiple workers causes an issue where request bodies can be escaped and sent multiple times.
```
[2017-05-02T10:08:43,486][DEBUG][logstash.filters.rest    ] Parsed request {:request=>[:post, "http://api/endpoint/url", {:header=>{"Content-Type"=>"application/json"}, :body=>{"ip"=>"1.2.3.4"}}]}
[2017-05-02T10:08:43,486][DEBUG][logstash.filters.rest    ] Parsed request {:request=>[:post, "http://api/endpoint/url", {:header=>{"Content-Type"=>"application/json"}, :body=>"{\"ip\":\"1.2.3.4\"}"}]}
[2017-05-02T10:08:43,486][DEBUG][logstash.filters.rest    ] Fetching request {:request=>[:post, "http://api/endpoint/url", {:header=>{"Content-Type"=>"application/json"}, :body=>"{\"ip\":\"1.2.3.4\"}"}]}
[2017-05-02T10:08:43,486][DEBUG][logstash.filters.rest    ] Fetching request {:request=>[:post, "http://api/endpoint/url", {:header=>{"Content-Type"=>"application/json"}, :body=>"\"{\\\"ip\\\":\\\"1.2.3.4\\\"}\""}]}
```

This may be an issue with the code in rest.rb line 211:
`    request[2][:body] = LogStash::Json.dump(request[2][:body]) if request[2].key?(:body)`

The issue is not present if I set `pipeline.workers: 1` in logstash.yml.

**Comment by gandalfb** [comment]
Hi, thank you for your bug report.
I believe it is related with [line 287](https://github.com/lucashenning/logstash-filter-rest/blob/master/lib/logstash/filters/rest.rb#L287) and a side-effect of using an `@` variable.

The idea was to omit a deep copy, but I guess this is the only thing that helps here.

I wonder if it is possible to create a testcase for that multithreading :thinking:

**Comment by gandalfb** [comment]
@tgeorgen do you have a `cli` oneliner to start logstash, which reproduces this?

That would help a lot. Thanks.

**Comment by gandalfb** [comment]
@tgeorgen 
I created a fix, I guess, and it would be great if you could do a check by replacing the `rest.rb` with this file: https://raw.githubusercontent.com/gandalfb/logstash-filter-rest/master/lib/logstash/filters/rest.rb

**Comment by rickys13** [comment]
Hi, I am seeing the same problem. Actually for me, the -w 1 is not changing this behavior, also I tried the yml file for pipeline.workers: 1 to no avail.
I did try by replacing the rb file suggested above and my service did not receive the request at all. I need to see what debug options I might have to turn on to trouble-shoot better. I am new to Logstash and dark-green on ruby.

Also, how am I supposed to pass a complex variable (or even an array) as shown below to either in body or params?

	  params => { 
		"key1" => "[
			{
				"filterType": "text",
				"text": "salmon"
			},
			{
				"filterType": "unique"
			}
		]"
	  }

**Comment by gandalfb** [comment]
Hi @rickys13 
For your complex variable: yes, you may use it in `ruby` syntax, not `string`. I added a test for this and found some bugs regarding finding `sprintf` and merge of interpolated fields.
A sample config can be found in the [testcase](https://github.com/gandalfb/logstash-filter-rest/blob/master/spec/filters/rest_spec.rb#L280)

For the parallel processing I am trying to reproduce with
```sh
bin/logstash --debug -e 'input { stdin{} } filter { rest { request => { url => "https://jsonplaceholder.typicode.com/posts" method => "post" params => { "key1" => [ { "filterType" => "text" "text" => "salmon" }, { "filterType" => "unique" } ] key2 => [ { "message" => "%{message}" } ] userId => "%{message}" } headers => { "Content-Type" => "application/json" } } target => 'rest' } } output {stdout { codec => rubydebug }}'
```

With multiple inputs, which should lead to parallel processing, I see correct behavior with the linked, updated `rest.rb` file.

**Comment by rickys13** [comment]
Hi @gandalfb 
Thank you for looking at this and adding a test to validate the syntax and response.

Sorry I tried one more time your rest.rb file and I got better behavior, so I changed my recent post.

**Comment by gandalfb** [comment]
This indicates that the rest.rb is not updated, as it seems like the old behavior I stumbled upon.
Do you use the cli one-liner from above?
What does the logstash debug log say?
Where do you replace the rest.rb?

Or add a local folder (logstash-filter-rest):
- Edit Logstash `Gemfile` and add the local plugin path, for example:
```ruby
gem "logstash-filter-awesome", :path => "/your/local/logstash-filter-awesome"
```

**Comment by rickys13** [comment]
@gandalfb Thank you! I think I did get your file working now (as I am stating in my edited message above). I think (for what I can tell so far) you DID fix the original issue regarding the "double escape".

I believe **we still have a little problem** regarding array, complex variables and variable substitution. I wonder if (assuming the issue is real) if this should be a separate one and not embedded in this original issue#22

Here is what I found:
If I set:
`	body => {
			filters => [
			{
			  "text" => "hard-coded-message"
			  "filterType" => "text"
			},
			{
			  "filterType" => "unique"
			}
		  ]
	}  
`
I get in my POST service request body (**this works fine, like your test does**):
`{
    "filters": [
        {
            "text": "hard-coded-message",
            "filterType": "text"
        },
        {
            "filterType": "unique"
        }
    ]
}`

BUT, if I set (with variable substitution inside the array and complex object):
`	body => {
			filters => [
			{
			  "text" => "%{message}"
			  "filterType" => "text"
			},
			{
			  "filterType" => "unique"
			}
		  ]
	}  
`
I get:
`{
    "filters": [
        {
            "text": "message1"
        }
    ]
}
`

**the filterType variables (both) get dropped**

**Comment by gandalfb** [comment]
Let's investigate this as a new issue.
Please create one with your detailed description. 

Eager to see this solved, as well. :-)

**Comment by rickys13** [comment]
done. Another question as I have your attention:

Is there a way to prevent stringifying the values?

if I set:
`		body => {
		  offset => null
		  pageSize => 1
		  saySomething => "hello"
		  preferMethod => false  
	  }  
`
I get:
`{
    "offset": "null",
    "pageSize": 1,
    "saySomething": "hello",
    "preferMethod": "false"
}`

only the integer was left alone but the boolean and null were transformed to strings.

I am new to GitHub, I am not sure what the proper vehicle to place a question is (apologize for that)

**Comment by tjgeorgen-zz** [comment]
Sorry for the late response. The new rest.rb seems to have fixed my issue. Thanks!

**Comment by gandalfb** [comment]
@tgeorgen great to hear, will create a PR. Thanks for verification.
@rickys13 if in doubt, create a new issue, to have one issue for one topic. This helps to keep the overview.
