### ISSUE TITLE
Logstash 5.5 Support

### ISSUE THREAD

**Issue by SMAPPER** [lucashenning/logstash-filter-rest#27]
Do you know what would need to be done to make this compatible with Logstash 5.5? It works on 5.x versions up to 5.4 but does not with 5.5. The install fails.

**Comment by gandalfb** [comment]
within `logstash-filter-rest.gemspec`
```sh
-  s.add_runtime_dependency 'logstash-mixin-http_client', '>= 2.2.4', '< 5.0.0'
+  s.add_runtime_dependency 'logstash-mixin-http_client', '>= 5.0.0', '< 6.0.0'
```

oh, that might be for 5.4.x only ...
I was able to use 5.5 and 5.4 with this small change.

**Comment by SMAPPER** [comment]
Much appreciated and thank you for the quick response.


Sincerely,

Justin Henderson
(312) 857-5755
Systems and Security Architect
GSE # 108, Cyber Guardian Red / Blue
http://www.linkedin.com/in/justinhenderson2014/

**Comment by gandalfb** [comment]
PR #28 created

**Comment by lucashenning** [comment]
New gem is online. Kudos to @gandalfb! Thank you!
