### ISSUE TITLE
Return only some values

### ISSUE THREAD

**Issue by lassehauballe** [lucashenning/logstash-filter-rest#37]
Hi 

I haven't been able to figure out if there is a way to only return certain fields from the JSON return. 

Lets say i query an API which returns: 
+ Title
+ Summary 
+ Date 

How to I tell the rest plugin that i only want to return the Summary field from the external api?

**Comment by matchbox10** [comment]
@povlteksttv Install [Prune](https://www.elastic.co/guide/en/logstash/current/plugins-filters-prune.html) Logstash plugin and whitelist the fields you want to keep
