### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by devnullsp** [lucashenning/logstash-filter-rest#4]
Hi
At first thanks for your work.

I tried to install but i had error. I use java version "1.7.0_95" & logstash-2.2.2:

```
gonzalo@ubuntu:~/logstash-2.2.2$ bin/plugin install  logstash-filter-rest
Validating logstash-filter-rest
Installing logstash-filter-rest
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 2.2.2)

  In Gemfile:
    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

```

**Comment by dajor** [comment]
Any feedback here - I have the same issue with logstash 2.3.1

**Comment by devnullsp** [comment]
Ruby do not know, but I think the configuration file has on the version and leaves no use in other more modern.

I have solved using a filter directly Ruby, although it has not been easy because as I say I do not know Ruby.

If you are interested send me a PM.

Regards,

**Comment by lucashenning** [comment]
@devnullsp @dajor Thank you guys for reporting this issue. The plugin wasn't compatible with Logstash > 2.0.0. I just changed the dependencies and published a [new version 0.1.6](https://rubygems.org/gems/logstash-filter-rest). Use the logstash-plugin-manager to install it:

```
$LS_HOME/bin/plugin uninstall logstash-filter-rest
$LS_HOME/bin/plugin install logstash-filter-rest
```

I successfully tried it with **Logstash 2.3.0**. Please let me know if you have any other issues.

**Comment by MikeBerryFR** [comment]
I've been fighting with this for a while now and stuck.  Plugin will not install, quoting this error: 

```
$> logstash-plugin install logstash-filter-rest
Validating logstash-filter-rest
Installing logstash-filter-rest
Error Bundler::InstallError, retrying 1/10
An error occurred while installing rest-client (2.0.0), and Bundler cannot continue.
Make sure that gem install rest-client -v '2.0.0' succeeds before bundling.
```

This repeats 10 times and gives up...

PC stats:
- Ubuntu 14.04.1 LTS
- Logstash v2.3
- Ruby v2.2.5 
- JRuby 1.9x and JRuby 9.1.2.0

I have tried several different versions of ruby and jruby.  I've ensured gem and bundle are installed/updated. I am certain the `gem install rest-client -v '2.0.0'` command works and installs. 

If I build the plugin myself, I'm seeing this error: 

```
$> logstash-plugin install --local logstash-filter-rest-0.1.6.gem
Installing logstash-filter-rest
fatal: Not a git repository (or any of the parent directories): .git
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "rest-client":
  In Gemfile:
    logstash-filter-rest (= 0.1.6) java depends on
      rest-client (>= 1.8.0) java
Could not find gem 'rest-client (>= 1.8.0) java', which is required by gem 'logstash-filter-rest (= 0.1.6) java', in any of the sources.
```

**Comment by MikeBerryFR** [comment]
For future users: 
- Change this line in the gemspec file and build the plugin locally.
- `-- s.add_runtime_dependency "rest-client", '>= 1.8.0'`
- `++ s.add_runtime_dependency "rest-client", '= 1.8.0'`

Follow manual/local installation procedure for logstash plugin installs from here to get this working in a LogStash Docker Container.

**Comment by lucashenning** [comment]
Thank you @MikeBerryFR for pointing this out. I'm gonna update the gem as soon as I find time to do so. For now, you guys might wanna use the manual solution mentioned by @MikeBerryFR.
