### ISSUE TITLE
Install with Logstash 2.3.1

### ISSUE THREAD

**Issue by dajor** [lucashenning/logstash-filter-rest#5]
Sorry but I have a issue when try to install your plugin with Logstash 2.3.1.

bin/plugin install logstash-filter-rest
The use of bin/plugin is deprecated and will be removed in a feature release. Please use bin/logstash-plugin.
Validating logstash-filter-rest
Installing logstash-filter-rest
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 2.3.1)

  In Gemfile:
    logstash-core-plugin-api (= 1.8.0) java depends on
      logstash-core (<= 2.3.1, >= 2.0.0) java

```
logstash-filter-rest (>= 0) java depends on
  logstash-core (< 2.0.0, >= 1.4.0) java

logstash-core (= 2.3.1) java
```

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

I tried to make a update but i can not find logstash-core 

Do you have any idea ?

So I would like to use your plugin to rewrite with Google Map Lat/Lng missing information to the data. 
And you plugin looks like the only solution i found right now. 

I have  a lots of data where i do not have these information in the address. 

best regards

Daniel

**Comment by lucashenning** [comment]
Fixed this in new release v0.1.6. Please see #4
